function App() {
  return (
    <>
      <header>
        <h1>Welcome to My Website</h1>
        <nav>
          <a href="#">Home</a>
          <a href="#">About</a>
          <a href="#">Services</a>
          <a href="#">Contact</a>
        </nav>
      </header>

      <main>
        <h2>About</h2>
        <p>This is the website</p>

        <h2>Services</h2>
        <ul>
          <li>Web Design</li>
          <li>Graphic Design</li>
          <li>Content Writing</li>
        </ul>
      </main>

      <footer>
        <p>
          &copy; 2023 My Website. All rights reserved. Generated by
          OpenAI&apos;s ChatGPT
        </p>
        <p>
          Contact: <a href="mailto:info@mywebsite.com">info@mywebsite.com</a>
        </p>
        <p>Follow us on social media:</p>
        <ul>
          <li>
            <a href="#">Facebook</a>
          </li>
          <li>
            <a href="#">Twitter</a>
          </li>
          <li>
            <a href="#">Instagram</a>
          </li>
        </ul>
      </footer>
    </>
  );
}

export default App;
