function Footer() {
  return (
    <footer>
      <p>
        &copy; 2023 My Website. All rights reserved. Generated by OpenAI&apos;s
        ChatGPT
      </p>
      <p>
        Contact: <a href="mailto:info@mywebsite.com">info@mywebsite.com</a>
      </p>
      <p>Follow us on social media:</p>
      <ul>
        <li>
          <a href="#">Facebook</a>
        </li>
        <li>
          <a href="#">Twitter</a>
        </li>
        <li>
          <a href="#">Instagram</a>
        </li>
      </ul>
    </footer>
  );
}

export default Footer;
